# -*- coding: utf-8 -*-
"""FinalFaceRecognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FLmfXc7qrBfIYgROenJpaOW5NzP8fwe5
"""

# ============================================================================
# CELL 1 – Install Dependencies
# ============================================================================

import sys
import io
if sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace', line_buffering=True)

# !pip install -q ultralytics insightface onnxruntime gdown opencv-python-headless

# ============================================================================
# CELL 2 – Imports & Device Setup
# ============================================================================

import numpy as np
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F
from scipy.optimize import linear_sum_assignment
from collections import deque, OrderedDict
import os
from pathlib import Path
import gdown
from ultralytics import YOLO
import matplotlib.pyplot as plt
from PIL import Image
import warnings
warnings.filterwarnings('ignore')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

torch.manual_seed(42)
np.random.seed(42)

# ============================================================================
# CELL 3 – Custom Re-ID Model  (unchanged from original tracker)
# ============================================================================

class ImprovedBasicBlock(nn.Module):
    def __init__(self, c_in, c_out, stride=1, use_se=True, reduction=16):
        super().__init__()
        self.conv1 = nn.Conv2d(c_in, c_out, 3, stride, 1, bias=False)
        self.bn1   = nn.BatchNorm2d(c_out)
        self.conv2 = nn.Conv2d(c_out, c_out, 3, 1, 1, bias=False)
        self.bn2   = nn.BatchNorm2d(c_out)

        self.use_se = use_se
        if use_se:
            self.se = nn.Sequential(
                nn.AdaptiveAvgPool2d(1),
                nn.Conv2d(c_out, c_out // reduction, 1),
                nn.ReLU(inplace=True),
                nn.Conv2d(c_out // reduction, c_out, 1),
                nn.Sigmoid()
            )
        self.downsample = nn.Sequential()
        if stride != 1 or c_in != c_out:
            self.downsample = nn.Sequential(
                nn.Conv2d(c_in, c_out, 1, stride, bias=False),
                nn.BatchNorm2d(c_out)
            )

    def forward(self, x):
        identity = self.downsample(x)
        out = F.relu(self.bn1(self.conv1(x)), inplace=True)
        out = self.bn2(self.conv2(out))
        if self.use_se:
            out = out * self.se(out)
        out += identity
        return F.relu(out, inplace=True)


class GeM(nn.Module):
    def __init__(self, p=3.0, eps=1e-6):
        super().__init__()
        self.p   = nn.Parameter(torch.ones(1) * p)
        self.eps = eps

    def forward(self, x):
        return F.adaptive_avg_pool2d(
            x.clamp(min=self.eps).pow(self.p), 1
        ).pow(1.0 / self.p)


class ImprovedDeepSortWideResNet(nn.Module):
    def __init__(self, num_features=128, num_classes=625,
                 dropout=0.3, use_se=True, use_gem=True):
        super().__init__()
        self.use_gem = use_gem
        self.stem = nn.Sequential(
            nn.Conv2d(3, 32, 3, 1, 1, bias=False), nn.BatchNorm2d(32), nn.ReLU(inplace=True),
            nn.Conv2d(32, 32, 3, 1, 1, bias=False), nn.BatchNorm2d(32), nn.ReLU(inplace=True)
        )
        self.maxpool = nn.MaxPool2d(3, 2, 1)
        self.layer1  = self._make_layer(32,  32,  2, stride=1, use_se=use_se)
        self.layer2  = self._make_layer(32,  64,  2, stride=2, use_se=use_se)
        self.layer3  = self._make_layer(64,  128, 2, stride=2, use_se=use_se)
        self.global_pool = GeM() if use_gem else nn.AdaptiveAvgPool2d(1)
        self.bn_neck   = nn.BatchNorm1d(128)
        self.dropout   = nn.Dropout(dropout) if dropout > 0 else nn.Identity()
        self.fc        = nn.Linear(128, num_features)
        self.classifier = nn.Linear(num_features, num_classes, bias=False)
        self._init_weights()

    def _make_layer(self, c_in, c_out, num_blocks, stride, use_se):
        layers = [ImprovedBasicBlock(c_in, c_out, stride, use_se)]
        for _ in range(1, num_blocks):
            layers.append(ImprovedBasicBlock(c_out, c_out, 1, use_se))
        return nn.Sequential(*layers)

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, (nn.BatchNorm2d, nn.BatchNorm1d)):
                nn.init.constant_(m.weight, 1); nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.normal_(m.weight, 0, 0.01)
                if m.bias is not None: nn.init.constant_(m.bias, 0)

    def forward(self, x, return_feature=False):
        x = self.stem(x); x = self.maxpool(x)
        x = self.layer1(x); x = self.layer2(x); x = self.layer3(x)
        x = self.global_pool(x).view(x.size(0), -1)
        x = self.bn_neck(x); x = self.dropout(x)
        features = F.normalize(self.fc(x), p=2, dim=1)
        if return_feature:
            return features
        return self.classifier(features)


class FeatureExtractor:
    def __init__(self, model_path='best_model.onnx', device='cpu'):
        import onnxruntime as ort
        print(f"Loading Re-ID ONNX model from {model_path}…")
        # CPUExecutionProvider is standard for hardware agnostic inference, CUDA is added if available
        opts = ort.SessionOptions()
        opts.intra_op_num_threads = 2
        opts.inter_op_num_threads = 1
        self.ort_session = ort.InferenceSession(model_path, sess_options=opts, providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
        print(f"  ✓ Re-ID ONNX model loaded")
        
        self.mean = np.array([0.485, 0.456, 0.406], dtype=np.float32).reshape(1,3,1,1)
        self.std  = np.array([0.229, 0.224, 0.225], dtype=np.float32).reshape(1,3,1,1)
        self.size = (128, 64)   # (H, W)

    def preprocess(self, img_crops):
        if len(img_crops) == 0:
            return np.empty((0, 3, *self.size), dtype=np.float32)
        processed = []
        for crop in img_crops:
            crop = cv2.resize(crop, (self.size[1], self.size[0]))
            crop = cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)
            t = np.transpose(crop, (2, 0, 1)).astype(np.float32) / 255.0
            processed.append(t)
        batch = np.stack(processed, axis=0)
        return (batch - self.mean) / self.std

    def extract(self, img, bboxes):
        if len(bboxes) == 0:
            return np.empty((0, 128))
        crops = []
        for bbox in bboxes:
            x1, y1, x2, y2 = map(int, bbox)
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(img.shape[1], x2), min(img.shape[0], y2)
            crop = img[y1:y2, x1:x2]
            crops.append(crop if crop.size > 0 else np.zeros((64,64,3), dtype=np.uint8))
        batch = self.preprocess(crops)
        return self.ort_session.run(None, {'input': batch})[0]

# ============================================================================
# CELL 4 – EnhancedFeatureExtractor
# ============================================================================

class EnhancedFeatureExtractor(FeatureExtractor):
    def __init__(self, model_path='best_model.onnx', device='cpu',
                 buffer_size=100, min_feature_quality=0.3):
        super().__init__(model_path, device)
        self.appearance_buffer  = []
        self.buffer_size        = buffer_size
        self.min_feature_quality = min_feature_quality
        self.use_multiscale     = True

    def assess_crop_quality(self, crop):
        if crop.size == 0: return 0.0
        h, w = crop.shape[:2]
        if h < 40 or w < 20: return 0.1
        aspect       = h / (w + 1e-6)
        aspect_score = max(0, min(1, 1.0 - abs(aspect - 2.0) / 2.0))
        gray         = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY)
        blur_score   = min(1.0, cv2.Laplacian(gray, cv2.CV_64F).var() / 100.0)
        bright_score = 1.0 - abs(np.mean(gray) - 128) / 128
        return aspect_score * 0.4 + blur_score * 0.4 + bright_score * 0.2

    def extract_multiscale(self, crop):
        feats = []
        for scale_crop in [crop]:
            r = cv2.resize(scale_crop, (self.size[1], self.size[0]))
            rgb = cv2.cvtColor(r, cv2.COLOR_BGR2RGB)
            t = (np.transpose(rgb, (2,0,1)).astype(np.float32)/255.0)[np.newaxis, ...]
            t = (t - self.mean) / self.std
            feats.append(self.ort_session.run(None, {'input': t})[0][0])

        if self.assess_crop_quality(crop) < 0.6 and self.use_multiscale:
            h, w = crop.shape[:2]
            zoom = crop[int(h*.1):int(h*.9), int(w*.1):int(w*.9)]
            if zoom.size > 0:
                r = cv2.resize(zoom, (self.size[1], self.size[0]))
                rgb = cv2.cvtColor(r, cv2.COLOR_BGR2RGB)
                t = (np.transpose(rgb, (2,0,1)).astype(np.float32)/255.0)[np.newaxis, ...]
                t = (t - self.mean) / self.std
                feats.append(self.ort_session.run(None, {'input': t})[0][0])

        return np.mean(np.stack(feats, axis=0), axis=0)

    def extract(self, img, bboxes, return_quality=False):
        if len(bboxes) == 0:
            return (np.empty((0,128)), []) if return_quality else np.empty((0,128))
        crops, qualities = [], []
        for bbox in bboxes:
            x1,y1,x2,y2 = map(int, bbox)
            x1,y1 = max(0,x1), max(0,y1)
            x2,y2 = min(img.shape[1],x2), min(img.shape[0],y2)
            crop = img[y1:y2, x1:x2]
            if crop.size > 0:
                crops.append(crop); qualities.append(self.assess_crop_quality(crop))
            else:
                crops.append(np.zeros((64,64,3), dtype=np.uint8)); qualities.append(0.0)

        feats = []
        for crop, q in zip(crops, qualities):
            if q > self.min_feature_quality:
                feats.append(self.extract_multiscale(crop))
            else:
                batch = self.preprocess([crop])
                ort_out = self.ort_session.run(None, {'input': batch})[0]
                feats.append(ort_out[0])
        features = np.stack(feats, axis=0)
        return (features, qualities) if return_quality else features

# ============================================================================
# CELL 5 – Kalman Filter & Track classes
# ============================================================================

class NSAKalmanFilter:
    """Noise-Scale Adaptive Kalman Filter (8-state: cx,cy,w,h,vx,vy,vw,vh)"""
    def __init__(self):
        dt = 1.0
        self.F = np.eye(8)
        for i in range(4): self.F[i, i+4] = dt
        self.H = np.eye(4, 8)
        self.Q = np.diag([1,1,1,1,0.01,0.01,0.0001,0.0001])
        self.R_base = np.diag([1.0, 1.0, 10.0, 10.0])
        self.P = np.eye(8) * 10
        self.x = np.zeros(8)

    def init(self, measurement):
        self.x[:4] = measurement

    def predict(self):
        self.x = self.F @ self.x
        self.P = self.F @ self.P @ self.F.T + self.Q
        return self.x[:4].copy()

    def update(self, measurement, confidence=1.0):
        alpha = max(0.1, min(1.0, confidence))
        R     = self.R_base / (alpha + 1e-6)
        S     = self.H @ self.P @ self.H.T + R
        K     = self.P @ self.H.T @ np.linalg.inv(S)
        innov = measurement - self.H @ self.x
        self.x = self.x + K @ innov
        self.P = (np.eye(8) - K @ self.H) @ self.P

    def get_state(self):
        return self.x[:4].copy()


class GMC:
    """Global Motion Compensation using ORB features"""
    def __init__(self, method='orb', downscale=2):
        self.method    = method
        self.downscale = downscale
        self.prevFrame = None
        self.prevKeyPoints  = None
        self.prevDescriptors = None
        if method == 'orb':
            self.detector = cv2.ORB_create(500)
            self.matcher  = cv2.BFMatcher(cv2.NORM_HAMMING)

    def apply(self, raw_frame, detections=None):
        H, W = raw_frame.shape[:2]
        frame = cv2.resize(raw_frame, (W//self.downscale, H//self.downscale))
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        transform = np.eye(2, 3)

        if self.prevFrame is None:
            self.prevFrame = frame
            keypoints, descriptors = self.detector.detectAndCompute(frame, None)
            self.prevKeyPoints   = keypoints
            self.prevDescriptors = descriptors
            return transform

        keypoints, descriptors = self.detector.detectAndCompute(frame, None)
        if (descriptors is not None and self.prevDescriptors is not None
                and len(keypoints) > 4 and len(self.prevKeyPoints) > 4):
            matches = self.matcher.knnMatch(self.prevDescriptors, descriptors, k=2)
            good = [m for m,n in matches if m.distance < 0.75*n.distance]
            if len(good) >= 4:
                src = np.float32([self.prevKeyPoints[m.queryIdx].pt for m in good]).reshape(-1,1,2)
                dst = np.float32([keypoints[m.trainIdx].pt for m in good]).reshape(-1,1,2)
                M, _ = cv2.estimateAffinePartial2D(src, dst, method=cv2.RANSAC)
                if M is not None:
                    transform = M.copy()
                    transform[:, 2] *= self.downscale

        self.prevFrame       = frame
        self.prevKeyPoints   = keypoints
        self.prevDescriptors = descriptors
        return transform


class Track:
    _count = 0

    def __init__(self, bbox, feature, track_id=None):
        if track_id is None:
            Track._count += 1
            self.track_id = Track._count
        else:
            self.track_id = track_id

        x1,y1,x2,y2 = bbox
        cx,cy = (x1+x2)/2, (y1+y2)/2
        w,h   = x2-x1, y2-y1

        self.kf = NSAKalmanFilter()
        self.kf.init(np.array([cx, cy, w, h]))
        self.features       = deque([feature], maxlen=30)
        self.hits           = 1
        self.age            = 1
        self.time_since_update = 0
        self.state          = 'tentative'
        self.trajectory     = deque(maxlen=30)
        self.trajectory.append((cx, cy))

    def predict(self):
        self.age += 1
        self.time_since_update += 1
        return self._xywh_to_xyxy(self.kf.predict())

    def update(self, bbox, feature, confidence=1.0):
        x1,y1,x2,y2 = bbox
        cx,cy = (x1+x2)/2, (y1+y2)/2
        w,h   = x2-x1, y2-y1
        self.kf.update(np.array([cx,cy,w,h]), confidence=confidence)
        self.features.append(feature)
        self.trajectory.append((cx, cy))
        self.hits += 1
        self.time_since_update = 0
        if self.state == 'tentative' and self.hits >= 3:
            self.state = 'confirmed'

    def mark_missed(self):
        if self.state == 'tentative':
            self.state = 'deleted'
        elif self.time_since_update > 30:
            self.state = 'deleted'

    def get_state(self):
        return self._xywh_to_xyxy(self.kf.get_state())

    def get_feature(self):
        return np.mean(self.features, axis=0)

    @staticmethod
    def _xywh_to_xyxy(xywh):
        cx,cy,w,h = xywh
        return np.array([cx-w/2, cy-h/2, cx+w/2, cy+h/2])


class EnhancedTrack(Track):
    def __init__(self, bbox, feature, track_id=None, quality=1.0):
        super().__init__(bbox, feature, track_id)
        self.detection_confidence = 1.0
        self.feature_quality      = quality
        self.consecutive_misses   = 0
        self.is_occluded          = False
        self.occlusion_frames     = 0
        self.last_seen_frame      = 0
        self.total_detections     = 1

    def predict(self):
        self.age += 1; self.time_since_update += 1; self.consecutive_misses += 1
        self.detection_confidence *= 0.95
        if self.consecutive_misses > 3 and self.detection_confidence > 0.5:
            self.is_occluded = True; self.occlusion_frames += 1
        if self.time_since_update > 5:
            self.kf.x[4:] *= 0.9
        return self._xywh_to_xyxy(self.kf.predict())

    def update(self, bbox, feature, quality=1.0):
        self.consecutive_misses = 0; self.is_occluded = False; self.occlusion_frames = 0
        self.detection_confidence = min(1.0, self.detection_confidence + 0.1)
        self.feature_quality = quality; self.total_detections += 1
        x1,y1,x2,y2 = bbox
        cx,cy = (x1+x2)/2, (y1+y2)/2; w,h = x2-x1, y2-y1
        self.kf.update(np.array([cx,cy,w,h]), confidence=self.detection_confidence)
        self.features.append(feature); self.trajectory.append((cx,cy))
        self.hits += 1; self.time_since_update = 0
        if self.state == 'tentative' and self.hits >= 3:
            self.state = 'confirmed'

    def mark_missed(self):
        self.consecutive_misses += 1; self.detection_confidence *= 0.9
        if self.state == 'tentative':
            self.state = 'deleted'
        elif self.detection_confidence < 0.2: self.state = 'deleted'
        elif self.time_since_update > 30:     self.state = 'deleted'
        elif self.is_occluded and self.time_since_update > 15: self.state = 'deleted'

    def get_confidence(self):
        return self.detection_confidence * 0.7 + min(1.0, self.total_detections/10.0) * 0.3


class MemoryAwareTrack(EnhancedTrack):
    def __init__(self, bbox, feature, track_id=None, quality=1.0, from_memory=False):
        super().__init__(bbox, feature, track_id, quality)
        self.from_memory          = from_memory
        self.memory_confirmed     = False
        self.high_quality_features = []

    def update(self, bbox, feature, quality=1.0):
        super().update(bbox, feature, quality)
        if quality > 0.5:
            self.high_quality_features.append(feature)
            if len(self.high_quality_features) > 10:
                self.high_quality_features.pop(0)

    def get_memory_feature(self):
        if self.high_quality_features:
            return np.mean(self.high_quality_features, axis=0)
        return self.get_feature()

# ============================================================================
# CELL 6 – BoTSORT / EnhancedBoTSORT / MemoryEnhancedBoTSORT
# ============================================================================

def _iou_distance(bboxes1, bboxes2):
    if len(bboxes1) == 0 or len(bboxes2) == 0:
        return np.zeros((len(bboxes1), len(bboxes2)))
    b1 = np.expand_dims(bboxes1, 1); b2 = np.expand_dims(bboxes2, 0)
    xi1 = np.maximum(b1[...,0], b2[...,0]); yi1 = np.maximum(b1[...,1], b2[...,1])
    xi2 = np.minimum(b1[...,2], b2[...,2]); yi2 = np.minimum(b1[...,3], b2[...,3])
    inter = np.maximum(0, xi2-xi1) * np.maximum(0, yi2-yi1)
    a1 = (b1[...,2]-b1[...,0]) * (b1[...,3]-b1[...,1])
    a2 = (b2[...,2]-b2[...,0]) * (b2[...,3]-b2[...,1])
    return 1 - inter / (a1 + a2 - inter + 1e-6)


def _cosine_distance(f1, f2):
    f1 = f1 / (np.linalg.norm(f1, axis=1, keepdims=True) + 1e-6)
    f2 = f2 / (np.linalg.norm(f2, axis=1, keepdims=True) + 1e-6)
    return 1 - np.dot(f1, f2.T)


class LongTermMemory:
    def __init__(self, max_identities=200, similarity_threshold=0.50,
                 features_per_id=128, quality_threshold=0.4):
        self.memory               = {}
        self.max_identities       = max_identities
        self.similarity_threshold = similarity_threshold
        self.features_per_id      = features_per_id
        self.quality_threshold    = quality_threshold

    def add_identity(self, track_id, feature, frame_num, quality=1.0):
        if quality < self.quality_threshold: return
        if track_id not in self.memory:
            self.memory[track_id] = {
                'features': deque([feature], maxlen=self.features_per_id),
                'last_seen': frame_num, 'total_appearances': 1, 'first_seen': frame_num
            }
        else:
            self.memory[track_id]['features'].append(feature)
            self.memory[track_id]['last_seen'] = frame_num
            self.memory[track_id]['total_appearances'] += 1

    def search_memory(self, feature, current_frame):
        best_id, best_score = None, self.similarity_threshold
        for tid, data in self.memory.items():
            stored = np.array(list(data['features']))
            sims   = np.dot(stored, feature)
            score  = 0.6 * np.mean(sims) + 0.4 * np.max(sims)
            if score > best_score:
                best_score = score; best_id = tid
        return best_id

    def cleanup_memory(self, current_frame, max_age=1000):
        if len(self.memory) > self.max_identities:
            sorted_ids = sorted(self.memory.items(),
                                key=lambda x: (x[1]['last_seen'], x[1]['total_appearances']))
            for tid, _ in sorted_ids[:len(self.memory) - self.max_identities]:
                del self.memory[tid]

    def get_memory_summary(self):
        if not self.memory: return "Memory: Empty"
        return (f"Memory: {len(self.memory)} IDs, "
                f"{sum(len(d['features']) for d in self.memory.values())} features")


class MemoryEnhancedBoTSORT:
    def __init__(self, feature_extractor, max_age=600, min_hits=5,
                 iou_threshold=0.4, lambda_iou=0.9, lambda_reid=0.1,
                 reid_threshold=0.30, reid_buffer_size=50,
                 memory_threshold=0.45, memory_size=200):
        self.feature_extractor = feature_extractor
        self.max_age           = max_age
        self.min_hits          = min_hits
        self.iou_threshold     = iou_threshold
        self.lambda_iou        = lambda_iou
        self.lambda_reid       = lambda_reid
        self.reid_threshold    = reid_threshold
        self.reid_buffer_size  = reid_buffer_size

        self.tracks     = []
        self.lost_tracks = []
        self.frame_count = 0
        self.gmc        = GMC(method='orb', downscale=2)

        self.long_term_memory = LongTermMemory(
            max_identities=memory_size,
            similarity_threshold=memory_threshold,
            features_per_id=10,
            quality_threshold=0.4
        )
        self.stats = {'memory_recoveries':0, 'reid_buffer_recoveries':0, 'new_ids_created':0}

    # ── helpers ──────────────────────────────────────────────────────────────

    def _camera_update(self, transform):
        for t in self.tracks:
            cx, cy = t.kf.x[0], t.kf.x[1]
            pt = cv2.transform(
                np.array([[cx, cy]], dtype=np.float32).reshape(1,1,2), transform
            ).reshape(2)
            t.kf.x[0], t.kf.x[1] = pt[0], pt[1]

    def _match(self, detections, det_features, qualities):
        if not self.tracks or len(detections) == 0:
            return [], list(range(len(detections))), []
        valid = [i for i,t in enumerate(self.tracks) if t.get_confidence() > 0.2]
        if not valid:
            return [], list(range(len(detections))), []
        tb = np.array([self.tracks[i].get_state()   for i in valid])
        tf = np.array([self.tracks[i].get_feature() for i in valid])
        db = detections[:, :4]
        qw = np.clip(np.array(qualities), 0.3, 1.0).reshape(-1,1)
        cost = self.lambda_iou * _iou_distance(tb, db) + \
               self.lambda_reid * _cosine_distance(tf, det_features) * qw.T
        r_ind, c_ind = linear_sum_assignment(cost)
        matches, um_tracks, um_dets = [], list(range(len(valid))), list(range(len(detections)))
        for r, c in zip(r_ind, c_ind):
            if cost[r, c] < 0.7:
                matches.append((valid[r], c))
                if r in um_tracks:   um_tracks.remove(r)
                if c in um_dets:     um_dets.remove(c)
        um_tracks = [valid[i] for i in um_tracks]
        return matches, um_dets, um_tracks

    def _reid_match(self, unmatched_dets, bboxes, features, qualities):
        if not self.lost_tracks or not unmatched_dets: return []
        lf = np.array([t.get_feature() for t in self.lost_tracks])
        df = np.array([features[i] for i in unmatched_dets])
        sim = 1 - _cosine_distance(lf, df)
        r_ind, c_ind = linear_sum_assignment(1 - sim)
        result = []
        for r, c in zip(r_ind, c_ind):
            if sim[r, c] > self.reid_threshold:
                result.append((r, unmatched_dets[c]))
        return result

    def _manage_tracks(self):
        active = []
        for t in self.tracks:
            if t.state == 'deleted':
                self.long_term_memory.add_identity(
                    t.track_id, t.get_memory_feature() if hasattr(t,'get_memory_feature') else t.get_feature(),
                    self.frame_count, quality=0.8
                )
                if (t.total_detections > 5 and t.get_confidence() > 0.4
                        and len(self.lost_tracks) < self.reid_buffer_size):
                    self.lost_tracks.append(t)
            else:
                active.append(t)
        self.tracks = active
        self.lost_tracks = [
            t for t in self.lost_tracks
            if (self.frame_count - t.last_seen_frame) < 60
        ]

    # ── main update ──────────────────────────────────────────────────────────

    def update(self, frame, detections):
        self.frame_count += 1
        transform = self.gmc.apply(frame, detections)
        self._camera_update(transform)

        for t in self.tracks: t.predict()

        if len(detections) > 0:
            bboxes               = detections[:, :4]
            features, qualities  = self.feature_extractor.extract(frame, bboxes, return_quality=True)
        else:
            bboxes    = np.empty((0,4))
            features  = np.empty((0,128))
            qualities = []

        # Stage 1: active tracks
        matches, um_dets, um_tracks = self._match(detections, features, qualities)
        for ti, di in matches:
            self.tracks[ti].update(bboxes[di], features[di], qualities[di])
            self.tracks[ti].last_seen_frame = self.frame_count
            if qualities[di] > 0.4:
                self.long_term_memory.add_identity(
                    self.tracks[ti].track_id, features[di], self.frame_count, qualities[di])

        # Stage 2: lost-track buffer
        if um_dets and self.lost_tracks:
            reid_matches = self._reid_match(um_dets, bboxes, features, qualities)
            for li, di in sorted(reid_matches, reverse=True):
                recovered = self.lost_tracks.pop(li)
                recovered.update(bboxes[di], features[di], qualities[di])
                recovered.state = 'confirmed'; recovered.time_since_update = 0
                self.tracks.append(recovered)
                self.stats['reid_buffer_recoveries'] += 1
                if qualities[di] > 0.4:
                    self.long_term_memory.add_identity(
                        recovered.track_id, features[di], self.frame_count, qualities[di])
                um_dets = [d for d in um_dets if d != di]

        # Stage 3: long-term memory
        still_unmatched = []
        for di in um_dets:
            if qualities[di] < 0.3:
                still_unmatched.append(di); continue
            mid = self.long_term_memory.search_memory(features[di], self.frame_count)
            if mid is not None:
                nt = MemoryAwareTrack(bboxes[di], features[di], track_id=mid,
                                      quality=qualities[di], from_memory=True)
                nt.last_seen_frame = self.frame_count
                nt.state = 'confirmed'; nt.memory_confirmed = True
                self.tracks.append(nt)
                self.stats['memory_recoveries'] += 1
                self.long_term_memory.add_identity(mid, features[di], self.frame_count, qualities[di])
            else:
                still_unmatched.append(di)

        for ti in um_tracks: self.tracks[ti].mark_missed()

        # Stage 4: brand-new IDs
        for di in still_unmatched:
            q = qualities[di] if di < len(qualities) else 0.5
            if q > 0.3:
                nt = MemoryAwareTrack(bboxes[di], features[di], quality=q, from_memory=False)
                nt.last_seen_frame = self.frame_count
                self.tracks.append(nt)
                self.long_term_memory.add_identity(nt.track_id, features[di], self.frame_count, q)
                self.stats['new_ids_created'] += 1

        self._manage_tracks()
        if self.frame_count % 100 == 0:
            self.long_term_memory.cleanup_memory(self.frame_count)

        outputs = []
        for t in self.tracks:
            if t.state == 'confirmed' and t.get_confidence() > 0.3:
                outputs.append([*t.get_state(), t.track_id])
        return np.array(outputs) if outputs else np.empty((0,5))

    def get_statistics(self):
        return {
            **self.stats,
            'memory_summary':    self.long_term_memory.get_memory_summary(),
            'active_tracks':     len(self.tracks),
            'lost_buffer':       len(self.lost_tracks),
            'memory_identities': len(self.long_term_memory.memory)
        }

# ============================================================================
# CELL 7 – Visualisation helpers  (extended to show role labels & trajectories)
# ============================================================================

def _make_palette(n=200):
    np.random.seed(42)
    palette = []
    for i in range(n):
        hue = (i * 0.618033988749895) % 1.0
        rgb = tuple(int(x*255) for x in plt.cm.hsv(hue)[:3])
        palette.append(rgb)
    return palette

COLORS = _make_palette(200)

# Fixed colours for roles so they are always visually distinct
ROLE_COLOR = {
    'patient':   (0,   80,  255),   # vivid blue
    'caregiver': (0,   220,  50),   # vivid green
    'unknown':   (60,  60,   60),   # dark grey – third party / unknown person
    None:        (180, 180, 180),   # light grey – unidentified (still building evidence)
}

ROLE_LABEL_TEXT = {
    'patient':   'PATIENT',
    'caregiver': 'CAREGIVER',
    'unknown':   'UNKNOWN',
    None:        None
}

def draw_role_tracks(frame, tracks, role_map):
    """
    Draw bounding boxes with role labels.
    Patient and caregiver get their assigned colors.
    Any other detected person is labeled UNKNOWN with a dark grey box.

    Parameters
    ----------
    frame     : BGR numpy array
    tracks    : Nx5 array  [x1,y1,x2,y2, track_id]
    role_map  : dict  {track_id: 'patient' | 'caregiver' | None}
    """
    result = frame.copy()
    for row in tracks:
        x1, y1, x2, y2, tid = row
        x1, y1, x2, y2, tid = int(x1), int(y1), int(x2), int(y2), int(tid)

        role = role_map.get(tid)
        # Any track not confirmed as patient/caregiver is displayed as UNKNOWN
        if role not in ('patient', 'caregiver'):
            role = 'unknown'

        color = ROLE_COLOR[role]
        label = ROLE_LABEL_TEXT[role]

        cv2.rectangle(result, (x1, y1), (x2, y2), color, 2)

        font       = cv2.FONT_HERSHEY_DUPLEX
        font_scale = 0.65
        thickness  = 2
        (tw, th), baseline = cv2.getTextSize(label, font, font_scale, thickness)

        # filled label background
        pad = 4
        top    = max(y1 - th - 2*pad, 0)
        bottom = top + th + 2*pad
        cv2.rectangle(result, (x1, top), (x1 + tw + 2*pad, bottom), color, -1)
        cv2.putText(result, label, (x1 + pad, bottom - pad - baseline//2),
                    font, font_scale, (255, 255, 255), thickness, cv2.LINE_AA)

    return result

def draw_trajectories(frame, tracker, role_map=None):
    """
    Draws movement trail ONLY for patient and caregiver tracks.
    Unknown / third-party persons are skipped so no extra dots appear.

    Parameters
    ----------
    frame    : BGR numpy array (modified in place)
    tracker  : MemoryEnhancedBoTSORT instance
    role_map : dict {track_id: "patient"|"caregiver"} – confirmed roles only.
               If None, no trajectories are drawn (safe fallback).
    """
    if role_map is None:
        return frame

    for t in tracker.tracks:
        # Only draw trajectories for confirmed patient / caregiver tracks
        role = role_map.get(t.track_id)
        if role not in ("patient", "caregiver"):
            continue

        if len(t.trajectory) < 2:
            continue

        # Use fixed role color so trail matches the bounding box color
        color  = ROLE_COLOR[role]
        points = list(t.trajectory)

        for i in range(1, len(points)):
            pt1 = (int(points[i-1][0]), int(points[i-1][1]))
            pt2 = (int(points[i][0]),   int(points[i][1]))
            # Skip degenerate segments (same point) – these render as stray dots
            if pt1 == pt2:
                continue
            # Line fades (thinner) as it gets older
            thickness = int(np.sqrt(20 / float(i + 1)) * 2)
            cv2.line(frame, pt1, pt2, color, max(1, thickness), cv2.LINE_AA)

    return frame

# ============================================================================
# CELL 8 – Upload Reference Images  (patient / caregiver)
# ============================================================================

import os
import shutil
import glob

def upload_images(role: str, source_paths=None, source_dir=None):
    """
    Copy reference images for a role ('patient' or 'caregiver') into the
    local  dataset/<role>/  folder so that FaceIdentityManager can build
    a face gallery.

    Usage (option A – explicit file list):
        upload_images('patient', source_paths=['photo1.jpg', 'photo2.png'])

    Usage (option B – copy everything from a directory):
        upload_images('caregiver', source_dir='C:/Users/Me/caregiver_photos')

    If neither argument is given, the function lists supported images
    already present in the target folder.
    """
    if role not in ('patient', 'caregiver'):
        print(f"❌ Invalid role '{role}'. Use 'patient' or 'caregiver'."); return

    target_dir = os.path.join('dataset', role)
    os.makedirs(target_dir, exist_ok=True)

    IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}
    copied = 0

    # Option A: explicit list of file paths
    if source_paths:
        for p in source_paths:
            if not os.path.isfile(p):
                print(f"  ⚠️  File not found, skipping: {p}"); continue
            ext = os.path.splitext(p)[1].lower()
            if ext not in IMAGE_EXTS:
                print(f"  ⚠️  Unsupported format ({ext}), skipping: {p}"); continue
            shutil.copy2(p, target_dir)
            copied += 1
            print(f"  ✓ Copied {os.path.basename(p)} → {target_dir}")

    # Option B: copy all images from a source directory
    elif source_dir:
        if not os.path.isdir(source_dir):
            print(f"❌ Source directory not found: {source_dir}"); return
        for fname in sorted(os.listdir(source_dir)):
            ext = os.path.splitext(fname)[1].lower()
            if ext in IMAGE_EXTS:
                shutil.copy2(os.path.join(source_dir, fname), target_dir)
                copied += 1
                print(f"  ✓ Copied {fname} → {target_dir}")

    # Show current state of the target folder
    existing = [f for f in os.listdir(target_dir)
                if os.path.splitext(f)[1].lower() in IMAGE_EXTS]
    print(f"\n  📂 {target_dir}: {len(existing)} image(s) total"
          f"  (newly copied: {copied})")
    if not existing:
        print(f"  ⚠️  No images found in {target_dir}. "
              f"Add reference photos before running the pipeline.")


INPUT_VIDEO_PATH = "input_video.mp4"

# ============================================================================
# CELL 11 – FaceIdentityManager  (InsightFace buffalo_l)
# ============================================================================

class FaceIdentityManager:
    """
    Uses InsightFace buffalo_l to:
      1. Build reference embeddings from uploaded patient/caregiver images.
      2. At runtime, detect faces inside person bounding boxes and compare
         them to the reference gallery to assign a role.

    Design decisions
    ─────────────────
    • Face detection runs on each person *crop* rather than the full frame;
      this is robust to scenes with many people and avoids cross-person confusion.
    • Similarity is cosine.  Thresholds are conservative so false positives
      are rare; unrecognised persons stay labelled "unknown".
    • Once a tracker ID is confirmed as patient or caregiver it is *locked*
      for the remainder of the video (stored in self.id_to_role).
    • Confirmation requires CONFIRM_HITS consecutive frames above threshold
      to suppress noise.
    """

    CONFIRM_HITS = 3          # frames above threshold needed to lock a role
    FACE_SIM_THRESHOLD = 0.30 # cosine similarity (InsightFace normed embeddings) — raised from 0.25 to reduce false matches

    def __init__(self, model_pack='buffalo_s', gpu_id=0):
        import insightface
        from insightface.app import FaceAnalysis
        print("Loading InsightFace model (buffalo_s)…")
        ctx = 0 if torch.cuda.is_available() else -1
        self.app = FaceAnalysis(
            name=model_pack, 
            allowed_modules=['detection', 'recognition'],
            providers=(['CUDAExecutionProvider'] if ctx == 0 else ['CPUExecutionProvider'])
        )
        self.app.prepare(ctx_id=ctx, det_size=(320, 320))
        print("  ✓ InsightFace ready")

        # Gallery: {role: [embedding, …]}
        self.gallery = {'patient': [], 'caregiver': []}

        # Runtime state
        self.track_sims = {}   # {track_id: {'patient': float, 'caregiver': float}}
        self.id_to_role = {}   # {track_id: 'patient'|'caregiver'}   (Current Frame)
        self.alpha      = 0.4  # EMA smoothing factor (faster response)
        
        # ReID-based appearance memory: when we confirm a face, store the body appearance
        self.role_reid_gallery = {'patient': [], 'caregiver': []}  # list of ReID embeddings per role
        self.reid_alpha = 0.45  # weight for ReID-based similarity updates (raised for stronger ReID reliance)

        # Role locking: once a track holds a role for CONFIRM_HITS consecutive
        # frames, it is "locked" — no other track can steal it.
        # {tid: {'role': str, 'held_frames': int, 'locked': bool}}
        self._role_locks = {}

        # Lost-role memory: when a LOCKED role disappears (track ID gone from
        # scene), remember it so we can transfer the role to a new track ID.
        # {role: {'reid_feats': [emb, ...], 'face_sims': dict, 'lost_frame': int}}
        self._lost_roles = {}
        self._frame_count = 0
        self.ROLE_TRANSFER_REID_THRESH = 0.35
        self.ROLE_TRANSFER_MAX_AGE = 300

    # ── gallery building ─────────────────────────────────────────────────────

    def _embed_image(self, img_bgr):
        """Return normalised face embedding from a BGR image, or None."""
        faces = self.app.get(img_bgr)
        if not faces:
            return None
        # Pick the largest face
        face  = max(faces, key=lambda f: (f.bbox[2]-f.bbox[0])*(f.bbox[3]-f.bbox[1]))
        emb   = face.normed_embedding.astype(np.float32)
        return emb / (np.linalg.norm(emb) + 1e-6)

    def build_gallery_from_folder(self, folder='dataset'):
        """
        Scans  dataset/patient/  and  dataset/caregiver/
        to build reference embeddings.
        """
        for role in ('patient', 'caregiver'):
            role_dir = os.path.join(folder, role)
            if not os.path.isdir(role_dir):
                print(f"  ⚠️  No folder found: {role_dir}"); continue
            loaded = 0
            for fname in sorted(os.listdir(role_dir)):
                if not fname.lower().endswith(('.jpg','.jpeg','.png','.bmp','.webp')):
                    continue
                img = cv2.imread(os.path.join(role_dir, fname))
                if img is None: continue
                emb = self._embed_image(img)
                if emb is not None:
                    self.gallery[role].append(emb)
                    loaded += 1
                else:
                    print(f"    ⚠️  No face detected in {fname}")
            print(f"  ✓ {role.capitalize()}: {loaded} reference face(s) loaded")

        assert (self.gallery['patient'] or self.gallery['caregiver']), \
            "❌ Gallery is empty – check dataset/ folders and image quality."

    # ── runtime identification ────────────────────────────────────────────────

    def _best_role_for_embedding(self, emb):
        """
        Compare emb against the gallery.
        Returns (best_role, best_similarity) or (None, 0).
        """
        best_role, best_sim = None, 0.0
        for role, refs in self.gallery.items():
            if not refs: continue
            sims = [float(np.dot(emb, r)) for r in refs]
            s    = max(sims)
            if s > best_sim:
                best_sim = s; best_role = role
        return best_role, best_sim

    def _get_face_in_crop(self, crop_bgr):
        """Detect face in a person crop; return normed embedding or None."""
        if crop_bgr is None or crop_bgr.size == 0:
            return None
        # Upscale very small crops for better detection
        h, w = crop_bgr.shape[:2]
        scale = 1.0
        if h < 80 or w < 40:
            scale = max(80/h, 40/w)
            crop_bgr = cv2.resize(crop_bgr, (int(w*scale), int(h*scale)))
        faces = self.app.get(crop_bgr)
        if not faces:
            return None
        face = max(faces, key=lambda f: (f.bbox[2]-f.bbox[0])*(f.bbox[3]-f.bbox[1]))
        emb  = face.normed_embedding.astype(np.float32)
        return emb / (np.linalg.norm(emb) + 1e-6)

    def update(self, frame_bgr, tracks, tracker=None):
        """
        Called once per frame.  Updates role assignments.

        Parameters
        ----------
        frame_bgr : full BGR frame
        tracks    : Nx5 numpy array [x1,y1,x2,y2, track_id]
        tracker   : MemoryEnhancedBoTSORT instance (for ReID feature access)

        Returns
        -------
        role_map  : dict {track_id: 'patient'|'caregiver'|None}
        """
        # Build a lookup of tracker's ReID features for each active track
        tracker_reid = {}
        if tracker is not None:
            for t in tracker.tracks:
                if t.state == 'confirmed':
                    tracker_reid[t.track_id] = t.get_feature()

        active_tids = []
        for row in tracks:
            x1, y1, x2, y2, tid = int(row[0]), int(row[1]), int(row[2]), int(row[3]), int(row[4])
            active_tids.append(tid)

            if tid not in self.track_sims:
                self.track_sims[tid] = {'patient': 0.0, 'caregiver': 0.0}

            # Extract person crop
            w, h = x2 - x1, y2 - y1
            x1c = max(0, int(x1 - w * 0.20))
            y1c = max(0, int(y1 - h * 0.20))
            x2c = min(frame_bgr.shape[1], int(x2 + w * 0.20))
            y2c = min(frame_bgr.shape[0], int(y2 + h * 0.20))
            crop = frame_bgr[y1c:y2c, x1c:x2c]

            face_updated = False
            emb = self._get_face_in_crop(crop)
            if emb is not None:
                sim_p = max([float(np.dot(emb, r)) for r in self.gallery['patient']] + [0.0])
                sim_c = max([float(np.dot(emb, r)) for r in self.gallery['caregiver']] + [0.0])
                
                # Ignore bad face crops (blurry, profile view) so they don't drag down the memory
                if max(sim_p, sim_c) > 0.25:
                    face_updated = True
                    if self.track_sims[tid]['patient'] == 0.0 and self.track_sims[tid]['caregiver'] == 0.0:
                        self.track_sims[tid]['patient'] = sim_p
                        self.track_sims[tid]['caregiver'] = sim_c
                    else:
                        self.track_sims[tid]['patient'] = (1 - self.alpha) * self.track_sims[tid]['patient'] + self.alpha * sim_p
                        self.track_sims[tid]['caregiver'] = (1 - self.alpha) * self.track_sims[tid]['caregiver'] + self.alpha * sim_c
                    
                    # Store this person's ReID (clothing) embedding alongside their best role
                    if tid in tracker_reid:
                        best_role = 'patient' if sim_p > sim_c else 'caregiver'
                        if max(sim_p, sim_c) > self.FACE_SIM_THRESHOLD:
                            reid_feat = tracker_reid[tid] / (np.linalg.norm(tracker_reid[tid]) + 1e-6)
                            self.role_reid_gallery[best_role].append(reid_feat)
                            # Keep gallery small (max 20 embeddings per role)
                            if len(self.role_reid_gallery[best_role]) > 20:
                                self.role_reid_gallery[best_role].pop(0)

            # FALLBACK: If no face detected, use ReID (clothing/body) appearance matching
            if not face_updated and tid in tracker_reid:
                reid_feat = tracker_reid[tid]
                reid_feat_norm = reid_feat / (np.linalg.norm(reid_feat) + 1e-6)
                
                reid_sim_p = 0.0
                reid_sim_c = 0.0
                if self.role_reid_gallery['patient']:
                    sims = [float(np.dot(reid_feat_norm, r)) for r in self.role_reid_gallery['patient']]
                    reid_sim_p = max(sims)
                if self.role_reid_gallery['caregiver']:
                    sims = [float(np.dot(reid_feat_norm, r)) for r in self.role_reid_gallery['caregiver']]
                    reid_sim_c = max(sims)
                
                # Only update if ReID match is strong enough AND discriminative.
                # The candidate must match one role clearly better than the other
                # to prevent cross-assignment (e.g. caregiver labeled as patient).
                if max(reid_sim_p, reid_sim_c) > 0.40:
                    margin = abs(reid_sim_p - reid_sim_c)
                    if margin > 0.05:  # must be at least 5% more similar to one role
                        # Scale ReID scores to face-similarity range
                        scaled_p = reid_sim_p * 0.85
                        scaled_c = reid_sim_c * 0.85
                        if self.track_sims[tid]['patient'] == 0.0 and self.track_sims[tid]['caregiver'] == 0.0:
                            self.track_sims[tid]['patient'] = scaled_p
                            self.track_sims[tid]['caregiver'] = scaled_c
                        else:
                            self.track_sims[tid]['patient'] = (1 - self.reid_alpha) * self.track_sims[tid]['patient'] + self.reid_alpha * scaled_p
                            self.track_sims[tid]['caregiver'] = (1 - self.reid_alpha) * self.track_sims[tid]['caregiver'] + self.reid_alpha * scaled_c

        # ══════════════════════════════════════════════════════════════
        # ROLE ASSIGNMENT  (locked-role-first, then greedy matching)
        # ══════════════════════════════════════════════════════════════
        role_map = {}
        assigned_roles = set()
        assigned_tids = set()
        prev_roles = dict(self.id_to_role)
        self.id_to_role = {}
        self._frame_count += 1
        active_set = set(active_tids)

        # ── Step 1: Carry forward roles in _role_locks ─────────────────
        # Tracks already in _role_locks get their role pre-assigned.
        # If held long enough, they become locked (cannot be stolen).
        for tid in list(self._role_locks):
            if tid not in active_set:
                continue  # track disappeared — handled in Step 4
            lock = self._role_locks[tid]
            role = lock['role']
            if role in assigned_roles:
                continue
            role_map[tid] = role
            self.id_to_role[tid] = role
            assigned_tids.add(tid)
            assigned_roles.add(role)
            lock['held_frames'] += 1
            # Promote to locked after CONFIRM_HITS consecutive frames
            if lock['held_frames'] >= self.CONFIRM_HITS and not lock['locked']:
                lock['locked'] = True
                score = self.track_sims.get(tid, {}).get(role, 0.0)
                src = "face" if score > 0.35 else "ReID"
                print(f"  🔒 Locked track {tid} → {role.upper()} (score {score:.3f}, via {src})")

        # ── Step 2: Greedy matching for UNLOCKED tracks ──────────────
        candidates = []
        for tid in active_tids:
            if tid in assigned_tids:
                continue  # already locked
            for role in ['patient', 'caregiver']:
                if role in assigned_roles:
                    continue  # role already taken by a locked track
                score = self.track_sims.get(tid, {}).get(role, 0.0)
                if score >= self.FACE_SIM_THRESHOLD:
                    candidates.append((score, tid, role))

        candidates.sort(reverse=True, key=lambda x: x[0])

        for score, tid, role in candidates:
            if tid in assigned_tids or role in assigned_roles:
                continue
            role_map[tid] = role
            self.id_to_role[tid] = role
            assigned_tids.add(tid)
            assigned_roles.add(role)
            # Start lock tracking (first frame with this role)
            self._role_locks[tid] = {'role': role, 'held_frames': 1, 'locked': False}
            src = "face" if score > 0.35 else "ReID"
            print(f"  🏷️  Tentative: track {tid} → {role.upper()} (score {score:.3f}, via {src}, locking in {self.CONFIRM_HITS - 1} frames)")
            # Remove from lost roles if this role was recovered
            self._lost_roles.pop(role, None)

        # ── Step 3: Role transfer for lost roles via ReID ────────────
        for role in ['patient', 'caregiver']:
            if role in assigned_roles:
                continue
            if role not in self._lost_roles:
                continue
            lost = self._lost_roles[role]
            if (self._frame_count - lost['lost_frame']) > self.ROLE_TRANSFER_MAX_AGE:
                del self._lost_roles[role]
                continue
            best_tid, best_sim = None, self.ROLE_TRANSFER_REID_THRESH
            lost_feats = lost['reid_feats']
            other_role = 'caregiver' if role == 'patient' else 'patient'
            for tid in active_tids:
                if tid in assigned_tids:
                    continue
                if tid not in tracker_reid:
                    continue
                feat = tracker_reid[tid]
                feat_norm = feat / (np.linalg.norm(feat) + 1e-6)
                sims = [float(np.dot(feat_norm, lf)) for lf in lost_feats]
                avg_sim = (0.5 * np.mean(sims) + 0.5 * np.max(sims)) if sims else 0.0
                # Discrimination check
                other_sim = 0.0
                if self.role_reid_gallery[other_role]:
                    other_sims = [float(np.dot(feat_norm, r)) for r in self.role_reid_gallery[other_role]]
                    other_sim = max(other_sims)
                if other_sim >= avg_sim:
                    continue
                if avg_sim > best_sim:
                    best_sim = avg_sim
                    best_tid = tid
            if best_tid is not None:
                role_map[best_tid] = role
                self.id_to_role[best_tid] = role
                assigned_tids.add(best_tid)
                assigned_roles.add(role)
                self.track_sims[best_tid] = dict(lost['face_sims'])
                self._role_locks[best_tid] = {'role': role, 'held_frames': self.CONFIRM_HITS, 'locked': True}
                print(f"  🔄 Role transfer: track {best_tid} → {role.upper()} (ReID sim {best_sim:.3f})")
                del self._lost_roles[role]

        # ── Step 4: Detect truly lost roles (track gone from scene) ──
        # Only save lost-role memory when a LOCKED track disappears from
        # active_tids. Role "theft" by another track does NOT trigger this.
        for tid in list(self._role_locks):
            if tid in active_set:
                continue  # track still alive
            lock = self._role_locks[tid]
            role = lock['role']
            if not lock['locked']:
                del self._role_locks[tid]
                continue  # wasn't locked yet, just discard
            # Track is gone AND was locked — save for transfer
            if role not in assigned_roles:
                feats = []
                if tid in tracker_reid:
                    feat = tracker_reid[tid] / (np.linalg.norm(tracker_reid[tid]) + 1e-6)
                    feats = [feat]
                elif self.role_reid_gallery.get(role):
                    feats = list(self.role_reid_gallery[role])
                if feats:
                    self._lost_roles[role] = {
                        'reid_feats': feats[-10:],
                        'face_sims': dict(self.track_sims.get(tid, {'patient': 0.0, 'caregiver': 0.0})),
                        'lost_frame': self._frame_count,
                    }
                    print(f"  ⚠️  Role '{role.upper()}' lost (track {tid} gone) — saved for transfer")
            del self._role_locks[tid]

        # Any remaining active tracks are Unknown
        for tid in active_tids:
            if tid not in assigned_tids:
                role_map[tid] = None
                
        return role_map

    def get_role_map(self):
        """Return the complete locked-role dictionary."""
        return dict(self.id_to_role)

# ============================================================================
# CELL 12 – RoleTracker  (high-level wrapper)
# ============================================================================

class RoleTracker:
    """
    High-level class that combines:
      - YOLO person detection
      - MemoryEnhancedBoTSORT tracking
      - FaceIdentityManager for patient/caregiver labelling

    Occlusion handling
    ──────────────────
    • The tracker's LongTermMemory ensures a person re-entering the frame
      after full occlusion gets back the same track_id.
    • Because roles are keyed on track_id and locked permanently, the
      label survives occlusion automatically – no extra logic required.
    • Camera-motion compensation (GMC/ORB) stabilises bounding boxes when
      the CCTV camera pans or shakes.
    """

    def __init__(self, reid_model_path, yolo_model='yolo11s.pt',
                 conf_threshold=0.5):
        print("="*70)
        print("  Initialising RoleTracker")
        print("="*70)

        self.conf_threshold = conf_threshold

        print("\n[1/3] Loading YOLO detector…")
        self.detector = YOLO(yolo_model)
        print("  ✓ YOLO loaded")

        print("\n[2/3] Loading Re-ID feature extractor…")
        self.feature_extractor = EnhancedFeatureExtractor(
            model_path=reid_model_path, device=str(device),
            buffer_size=500, min_feature_quality=0.05
        )
        print("  ✓ Feature extractor loaded")

        print("\n[3/3] Initialising MemoryEnhancedBoTSORT tracker…")
        self.tracker = MemoryEnhancedBoTSORT(
            feature_extractor=self.feature_extractor,
            max_age=6000, min_hits=5,
            iou_threshold=0.4, lambda_iou=0.9, lambda_reid=0.1,
            reid_threshold=0.30, reid_buffer_size=150,
            memory_threshold=0.40, memory_size=6000
        )
        print("  ✓ Tracker ready (memory-enhanced, long-term buffer active)")

        # Face identity manager is built lazily in run()
        self.face_id_manager = None

    def build_gallery(self, dataset_dir='dataset'):
        print("\nBuilding face gallery from reference images…")
        self.face_id_manager = FaceIdentityManager()
        self.face_id_manager.build_gallery_from_folder(dataset_dir)
        print("  ✓ Gallery built")

    def process_frame(self, frame):
        """
        Detect → track → identify.

        Returns
        -------
        tracks   : Nx5  [x1,y1,x2,y2, track_id]
        role_map : dict {track_id: 'patient'|'caregiver'|None}
        """
        results    = self.detector(frame, verbose=False)[0]
        detections = []
        for box in results.boxes:
            if int(box.cls[0]) == 0:   # class 0 = person
                x1,y1,x2,y2 = box.xyxy[0].cpu().numpy()
                conf         = float(box.conf[0].cpu().numpy())
                if conf > self.conf_threshold:
                    detections.append([x1,y1,x2,y2,conf])

        det_arr = np.array(detections) if detections else np.empty((0,5))
        tracks  = self.tracker.update(frame, det_arr)

        if tracks.shape[0] == 0:
            return tracks, {}

        role_map = (self.face_id_manager.update(frame, tracks)
                    if self.face_id_manager else {})

        return tracks, role_map

# ============================================================================
# CELL 13 – run_patient_caregiver_tracking()
# ============================================================================

def run_patient_caregiver_tracking(
    video_path        = 'input_video.mp4',
    output_path       = 'output_role_tracked.mp4',
    reid_model_path   = 'best_model.pth',
    dataset_dir       = 'dataset',
    conf_threshold    = 0.4,
    max_frames        = None,
    show_trajectories = True
):
    """
    End-to-end function: reads video, runs tracking + role identification,
    writes annotated output video.

    Parameters
    ----------
    video_path      : path to input video (mp4 / avi / …)
    output_path     : where to write the annotated output
    reid_model_path : your custom .pth Re-ID model
    dataset_dir     : root folder containing dataset/patient/ and dataset/caregiver/
    conf_threshold  : YOLO detection confidence cutoff
    max_frames      : process only this many frames (None = all)
    show_trajectories: draw motion trail on tracked persons
    """

    # ── pre-flight checks ────────────────────────────────────────────────────
    for path, name in [(video_path,'Video'), (reid_model_path,'Re-ID model')]:
        if not os.path.exists(path):
            print(f"❌ {name} not found: {path}"); return

    # ── initialise components ────────────────────────────────────────────────
    role_tracker = RoleTracker(reid_model_path=reid_model_path,
                               conf_threshold=conf_threshold)
    role_tracker.build_gallery(dataset_dir=dataset_dir)

    # ── open video ───────────────────────────────────────────────────────────
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("❌ Cannot open video"); return

    fps    = int(cap.get(cv2.CAP_PROP_FPS)) or 25
    W      = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H      = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total  = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if max_frames: total = min(total, max_frames)

    print(f"\n▶  Video: {W}×{H} @ {fps} FPS  ({total} frames)")
    print(f"▶  Output: {output_path}\n")

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    writer = cv2.VideoWriter(output_path, fourcc, fps, (W, H))

    # Persistent role map that accumulates across the video
    global_role_map = {}

    frame_idx = 0
    while True:
        ret, frame = cap.read()
        if not ret or (max_frames and frame_idx >= max_frames):
            break

        tracks, frame_role_map = role_tracker.process_frame(frame)

        # Merge new role discoveries into global map (never overwrite a lock)
        for tid, role in frame_role_map.items():
            if role is not None and tid not in global_role_map:
                global_role_map[tid] = role
        # Also pull locked roles from FaceIdentityManager
        if role_tracker.face_id_manager:
            for tid, role in role_tracker.face_id_manager.get_role_map().items():
                global_role_map[tid] = role

        # ── draw ─────────────────────────────────────────────────────────────
        vis = draw_role_tracks(frame, tracks, global_role_map)

        if show_trajectories:
            vis = draw_trajectories(vis, role_tracker.tracker, role_map=global_role_map)

        # ── HUD overlay ──────────────────────────────────────────────────────
        stats = role_tracker.tracker.get_statistics()

        patient_found   = any(r=='patient'   for r in global_role_map.values())
        caregiver_found = any(r=='caregiver' for r in global_role_map.values())

        hud_lines = [
            (f"Frame {frame_idx+1}/{total}  |  Active tracks: {len(tracks)}",
             (10, 28),  (0, 255, 0)),
            (f"Memory IDs: {stats['memory_identities']}  |  "
             f"Mem-recoveries: {stats['memory_recoveries']}",
             (10, 54),  (0, 255, 255)),
            (f"Patient {'✓ FOUND' if patient_found else '— searching'}  |  "
             f"Caregiver {'✓ FOUND' if caregiver_found else '— searching'}",
             (10, 80),  (255, 230, 100)),
        ]
        for text, pos, color in hud_lines:
            cv2.putText(vis, text, pos,
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2, cv2.LINE_AA)

        writer.write(vis)

        if (frame_idx + 1) % 30 == 0:
            print(f"  [{frame_idx+1}/{total}]  active={len(tracks)}  "
                  f"patient={'✓' if patient_found else '?'}  "
                  f"caregiver={'✓' if caregiver_found else '?'}  "
                  f"mem_recoveries={stats['memory_recoveries']}")

        frame_idx += 1

    cap.release(); writer.release()

    # ── final summary ────────────────────────────────────────────────────────
    stats = role_tracker.tracker.get_statistics()
    print("\n" + "="*70)
    print("  TRACKING COMPLETE")
    print("="*70)
    print(f"  Output video  : {output_path}")
    print(f"  Frames processed: {frame_idx}")
    print(f"  Total track IDs  : {Track._count}")
    print(f"\n  Role assignments (locked for entire video):")
    for tid, role in sorted(global_role_map.items()):
        print(f"    Track {tid:>4d}  →  {role.upper()}")
    print(f"\n  Memory statistics:")
    print(f"    {stats['memory_summary']}")
    print(f"    Memory recoveries : {stats['memory_recoveries']}")
    print(f"    Buffer recoveries : {stats['reid_buffer_recoveries']}")
    print(f"    New IDs created   : {stats['new_ids_created']}")
    print("="*70)

# ============================================================================
# Entry point (notebook or script)
# ============================================================================

if __name__ == '__main__':
    # ── Step 1: upload reference images ─────────────────────────────────────
    # Place patient/caregiver face images in  dataset/patient/  and
    # dataset/caregiver/  OR use upload_images() to copy them:
    #
    #   upload_images('patient',   source_paths=['patient_photo.jpg'])
    #   upload_images('caregiver', source_paths=['caregiver_photo.jpg'])
    #   upload_images('patient',   source_dir='path/to/patient_photos')
    #   upload_images('caregiver', source_dir='path/to/caregiver_photos')

    # ── Step 2: run! ────────────────────────────────────────────────────────
    Track._count = 0   # reset IDs
    run_patient_caregiver_tracking(
        video_path      = INPUT_VIDEO_PATH,
        output_path     = 'output_role_tracked.mp4',
        reid_model_path = 'best_model.pth',
        dataset_dir     = 'dataset',
        conf_threshold  = 0.4,
        max_frames      = None,
        show_trajectories = True
    )
